
loding lib
```{r}
library(tidyverse)
```

lading data
```{r}
cake_tb <- read_csv("clean_data/cake_clean.csv")
```
Which cake has the most cocoa in it?

```{r}
cake_tb %>% 
  select(cake,ingredient,amount) %>% 
  filter(ingredient == "Cocoa") %>% 
  summarise(max_cocoa = max(amount,na.rm = TRUE))
```

For sponge cake, how many cups of ingredients are used in total?
```{r}
cake_tb %>% filter(cake == "Sponge",measure=="cup") %>% 
  summarise(total_cups_of_ingrediens = sum(amount,na.rm = TRUE))
```

How many ingredients are measured in teaspoons?
```{r}
cake_tb %>% 
  filter(measure=="teaspoon") %>% 
  distinct(ingredient) %>% 
  nrow()
  
```

Which cake has the most unique ingredients?
```{r}
cake_tb %>% 
  select(cake,ingredient,amount) %>%
  filter(!is.na(amount)) %>% 
  group_by(cake) %>% 
  summarise(num_of_ingridients = n()) %>% 
  arrange(desc(num_of_ingridients))
  
  
```

Which ingredients are used only once?
```{r}
cake_tb %>% 
  select(ingredient,amount) %>% 
  filter(!is.na(amount)) %>% 
  group_by(ingredient) %>% 
  summarise(num_ocurences = n()) %>% 
  arrange(num_ocurences) %>% 
  filter(num_ocurences == 1)
```










