```{r}
library(dplyr)
library(lubridate)
library(tidyverse)
library(tsibble)
library(tsibbledata)
library(feasts)
library(nycflights13)


date1 <- ymd_hms("2017-04-22 22:01:18")
date2 <- ymd_hms("2001-11-07 10:09:56")
```
Q1
```{r}
year(date1)
month(date1, label = TRUE, abbr = FALSE)
mday(date1)
yday(date1)
wday(date1,label = TRUE,week_start = 1)
```
Q2
```{r}
next_fortnight <- date1 + days(14)
previous_decade <- date2 - years(10)
```

Q3
```{r}
this_year <- today() 
interval_years <- lubridate::interval(this_year,previous_decade)
```
Q4
```{r}
nyc_date1 <- with_tz(date1, tzone = "America/New_York")
nyc_date2 <- with_tz(date2, tzone = "America/New_York")

```
Q5
```{r}
head(flights)
```
```{r}
flights %>% 
  mutate(departure_date = make_datetime(year,month,day,hour,minute))
```
Q6 
```{r}
head(weather)
```

```{r}
tail(weather)
```



```{r}
dim(weather)
```
```{r}
str(weather)
```



```{r}
weather %>% 
  select(time_hour,origin,temp,dewp,humid,precip,pressure)
```
Weather dataset contains series of weather data like temp,humidity, precipitation etc. collected between
2013-01-01 01:00:00 and 2013-12-30 18:00:00 (full year ). Index:time_hour, key: origin

Q7
```{r}
weather <- weather %>% 
  select(time_hour,origin,temp,dewp,humid,precip,pressure) 
 
```

```{r}
weather_tsbl <- as_tsibble(weather, key = origin, index = time_hour)

```

Q8
```{r}
weather_tsbl %>% 
  mutate(year = year(time_hour),
         month = month(time_hour)) %>% 
  ggplot()+
  aes(time_hour,temp) %>% 
  geom_line(col = "green") +
  facet_grid(~origin)



```

Q9
```{r}
weather_rolling <- weather_tsbl %>% 
  group_by_key() %>% 
  mutate(temp_ma = slide_dbl(temp, ~ mean(., na.rm = TRUE), .size = 500))

weather_rolling %>% 
  ggplot()+
    geom_line(aes(x = time_hour, y = temp), colour = "grey") +
    geom_line(aes(x= time_hour, y = temp_ma),color = "red")+
  facet_wrap(~origin)

```






Q10
```{r}
weather_tsbl %>% 
  mutate(year = year(time_hour),
         month = month(time_hour)) %>% 
  ggplot()+
  aes(day(time_hour),temp) %>% 
  geom_line(col = "green") +
  facet_grid(~origin)
```

Q11
```{r}

```
Q12.
```{r}

```

