---
title: "R Notebook"
output: html_notebook
---


Functions 2.2.1
```{r}
multiplayer <- function(x){
  result <- x * 15 + 4
  return(result)
  
}
```

Functions 2.2.1 -Testing.

```{r}
multiplayer(1)
multiplayer(2)
multiplayer(3)
```

Q2.2.2 Birds Function
```{r}
bird_checker <- function(x){
  birds <- c("duck","goose","pigeon")
  if(x %in% birds){
    return("bird")
  }else {
    return("not bird")
  }
}

```

Q2.2.2 Birds Function -testing

```{r}
bird_checker(5)
```



Q 2.2.3 Multiply by 10
```{r}
multiply_by_10 <- function(x){
  if(is.numeric(x)){
    return(x*10)
  }else{
    return(print("Invalid input"))
  }
}
```

Q 2.2.3 Multiply by 10 -Testing
```{r}
multiply_by_10(2)
multiply_by_10(5.3)
multiply_by_10("x")
multiply_by_10(7)




```

Q2.3.1 ifelse
```{r}
sizes <- c(13, 15, 10, 8, 22)
big <- c()
small <- c()
#x <- sizes[1:length(sizes)]
ifelse(sizes >10,
            "Big",
            "Small" 
)



```
Q2.3.1 recode()
```{r}
sizes <- c(13, 15, 10, 8, 22)
sizes_char <- as.character(sizes)

#sizes_factor <- factor(sizes,levels = as.character(sizes))
#sizes_factor
dplyr::recode(sizes,
              "8" = "Small",
              "10" = "Small",
              "13" = "BIG",
              "15" = "BIG",
              "22" = "BIG")
```


Q2.3.1 case_when()
```{r}
sizes <- c(13, 15, 10, 8, 22)
dplyr::case_when(
  sizes >10 ~ "Big",
  TRUE ~ "Small"
)

```
 Q2.3.2 ifelse()
```{r}
fruit <- c("apple", "apple", "banana", "cherry", "cherry")
ifelse(fruit == "apple","alpaca",
       ifelse(fruit == "banana","bonobo",
              ifelse(fruit == "cherry","chipmunk","boo")))

```
 
Q2.3.2 recode()
```{r}
fruit <- c("apple", "apple", "banana", "cherry", "cherry")
dplyr::recode(fruit,
              "apple"= "alpaca",
              "banana"="bonobo",
              "cherry"="chipmunk"

)

```
Q2.3.2 case_when()
```{r}
fruit <- c("apple", "apple", "banana", "cherry", "cherry")
dplyr::case_when(
    fruit == "apple" ~ "alpaca",
    fruit == "banana" ~ "bonobo",
    fruit == "cherry" ~ "chipmunk"
)

```

Q 2.3.3 ifelse
```{r}
wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)
ifelse(wife_age == husband_age, "Same age",
       ifelse(wife_age > husband_age, "Wife older","Husbend older") )
```
Q 2.3.3 recode()
```{r}
wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)


age_relation <- dplyr::recode(as.character(wife_age>husband_age),
              "TRUE" = "Wife older",
             "FALSE" = "Husband older")
age_relation[4] <- "Same age"
age_relation
```
Q 2.3.3 case_when()
```{r}
wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)
dplyr::case_when(
  wife_age > husband_age  ~"Wife older",
  wife_age < husband_age ~ "Husband older",
  TRUE ~ "Same age"
)

```


Q 2.4
```{r}
my_list <- list(
  4,
  "apple",
  10.5,
  c("is", "an", "apple"),
  "apple",
  c("i", "like", "apples"),
  8
)
```

Q 2.4.1 for loop 
```{r}
for (item in my_list){
  if(is.character(item)){
    print(item)
  }
}
```

2.4.2 while loop
```{r}
x <- 1
while (x < length(my_list)){
  if(is.character(my_list[[x]])){
      print(my_list[[x]])
    }
  x <- x + 1
  }

```
Q 2.4.3
```{r}
#rm(full_vector)
full_vector <- c()

x <- 1
while (x < length(my_list)){
  if(is.character(my_list[[x]]) && length(my_list[[x]]) > 1 ){
      full_vector <- c(my_list[[x]],full_vector)
      
    }
  x <- x + 1
}
full_vector

rm(full_vector)
```
Q3.1 12 by 12 matrix
```{r}
vec_num <- c()
for (i in 1:12) {
  for (z in 1:12) {
    vec_num <- c(vec_num, i * z)
  }
}
by_matrix <- matrix(vec_num,12,12)
colnames(by_matrix) <- 1:12
rownames(by_matrix) <- 1:12
by_matrix

```
Q 3.2
```{r}

histogram_func <- function(vec){
  num_of_stars <- c()
  words <- strsplit(vec," ")
  print_stars <- function(x){
      cat("|",rep("*",x), "\n")
      }
  for(i in words[[1]]){
      num_of_stars <- c(num_of_stars,nchar(i)) 
    }

  for(i in num_of_stars){
    print_stars(i)
    }
}





```

Q 3.2 Test.
```{r}
histogram_func("Very long sentence that never ends")
```




