---
title: "R Notebook"
output: html_notebook
---
PART ONE 
Q1
```{r}
stock_prices <- c(23, 27, 23, 21, 34, 24, 25, 30, 37, 30)
day_of_week <- rep(c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"), times =  2)

```

```{r}
stock_prices
day_of_week
```

Q2
```{r}
day_of_week_factor <- as.factor(day_of_week)
named_stock_prices <- setNames(stock_prices,day_of_week)
```

```{r}
class(day_of_week_factor)
named_stock_prices
```


Q3
```{r}
stock_data <- data.frame(stock_prices,day_of_week)
View(stock_data)
```

Q4
```{r}
stock_list <- list(price = stock_prices,
                   weekdays = day_of_week,
                   data = stock_data)
```

```{r}
stock_list
```

PART 2 
Q1
```{r}
stock_prices
stock_prices[c(4,5,6)]
stock_prices[stock_prices > 30]
```

Q2
```{r}
stock_data$day_of_week

```

```{r}
stock_data[stock_data$stock_prices < 25,]

```


```{r}
stock_data[,1 ]
```


```{r}
stock_data[3, ]

```
```{r}
stock_data[1,3]
```

Q4 
```{r}
stock_list$data

```



EXTENSION
```{r}
install.packages('tidyquant')
install.packages('lubridate')

```

```{r}

library(tidyquant)
```



```{r}
 help(tidyquant)
browseVignettes(package = "tidyquant")
```


```{r}
data("FANG")

```
```{r}
amazon <-tq_get('AMZN', from = '2020-01-01')

```

```{r}
amazon
```


```{r}
edited_amazon <- data.frame(amazon$date,amazon$close)

```


```{r}
edited_amazon
```

```{r}
avarage_closing_price <- mean(amazon$close)
closing_higher_avarage <-amazon[amazon$close > avarage_closing_price,] 

```
```{r}
avarage_closing_price

closing_higher_avarage
```



